spring:
  security:
    user:
      name: admin
      password: admin
      
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:admin@localhost:15001/eureka/
    

server:
  port: 15001